name: Build and deploy to GCP Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud --quiet auth configure-docker

      - name: Build container image
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/alemeno-backend:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/alemeno-backend:${{ github.sha }}
          gcloud run deploy alemeno-backend --image $IMAGE --region ${{ secrets.GCP_REGION }} --platform managed --allow-unauthenticated
