name: Build and deploy to GCP Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: |
          gcloud --quiet auth configure-docker

      - name: Build container image
        run: |
          if [ -z "${{ secrets.GCP_PROJECT }}" ]; then
            echo "Missing GCP_PROJECT secret"; exit 1; fi
          # use short sha (first 12 chars) and sanitize tag to be Docker-friendly
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-12)
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/alemeno-backend:${SHORT_SHA}
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-12)
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT }}/alemeno-backend:${SHORT_SHA}
          gcloud run deploy alemeno-backend --image "$IMAGE" --region ${{ secrets.GCP_REGION }} --platform managed --allow-unauthenticated
