name: verify-requirements

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip-tools cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-verify-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-cache-verify-

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Quick smoke check
        run: |
          python - <<'PY'
          import sys
          print('Python', sys.version)
          import pkgutil
          for pkg in ('flask','streamlit'):
              found = pkgutil.find_loader(pkg) is not None
              print(pkg, 'found=', found)
          PY
